Repository Dev-FE-3/toy-project3-team1, pull requests merged in 2025-04, with the labels that each got.

#2 feat: router 기본 설정 세팅 #1
  .github/ISSUE_TEMPLATE/basic.md
  .github/ISSUE_TEMPLATE/issue_form.yml
  .github/PULL_REQUEST_TEMPLATE.md
  src/App.tsx
  src/main.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/PlaylistCollection/PlaylistCollectionpage.tsx
  src/pages/PlaylistDetail/PlaylistDetailPage.tsx
  src/pages/PlaylistForm/PlaylistFormPage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/Signup/SignupPage.tsx
  src/router.tsx
  src/shared/components/layout/Layout.tsx
  src/shared/model/styles/globals.css
  src/vite-env.d.ts
Labels: 🚀 feat

#7 Refactor : 폰트 로딩 최적화
  index.html
  public/fonts/NotoSansKR-Medium.woff2
  public/fonts/NotoSansKR-Regular.woff2
  src/assets/fonts/NotoSansKR-Black.woff
  src/assets/fonts/NotoSansKR-Black.woff2
  src/assets/fonts/NotoSansKR-Bold.woff
  src/assets/fonts/NotoSansKR-Bold.woff2
  src/assets/fonts/NotoSansKR-ExtraBold.woff
  src/assets/fonts/NotoSansKR-ExtraBold.woff2
  src/assets/fonts/NotoSansKR-ExtraLight.woff
  src/assets/fonts/NotoSansKR-ExtraLight.woff2
  src/assets/fonts/NotoSansKR-Light.woff
  src/assets/fonts/NotoSansKR-Light.woff2
  src/assets/fonts/NotoSansKR-Medium.woff
  src/assets/fonts/NotoSansKR-Regular.woff
  src/assets/fonts/NotoSansKR-SemiBold.woff
  src/assets/fonts/NotoSansKR-SemiBold.woff2
  src/assets/fonts/NotoSansKR-Thin.woff
  src/assets/fonts/NotoSansKR-Thin.woff2
  src/shared/model/styles/font.css
  src/shared/model/styles/globals.css
Labels: 🔨 refactor

#11 Feat: YouTube 영상 정보 조회 기능 개발 #10
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/shared/hooks/useYouTubeVideo.ts
  src/shared/model/types/youtube.type.ts
  src/shared/queries/useYouTubeVideoQuery.ts
  src/shared/services/youtubeVideoApi.ts
Labels: 🚀 feat

#9 공통 컴포넌트 작업 점검
  public/images/logo.svg
  src/pages/DesignSystem/DesignSystem.tsx
  src/pages/Login/LoginPage.tsx
  src/router.tsx
  src/shared/components/Avatar/Avatar.tsx
  src/shared/components/BackButton/BackButton.tsx
  src/shared/components/BottomNav/BottomNav.tsx
  src/shared/components/HashTag/HashTag.tsx
  src/shared/components/MoreMenu/MoreMenu.tsx
  src/shared/components/SearchBar/SearchBar.tsx
  src/shared/components/StatusButton/StatusButton.tsx
  src/shared/components/TabMenu/TabMenu.tsx
  src/shared/components/VideoPlayer/VideoPlayer.tsx
  src/shared/components/layout/Layout.tsx
  src/shared/components/stats/BookmarkIcon.tsx
  src/shared/components/stats/LikeIcon.tsx
  src/shared/components/ui/badge.tsx
  src/shared/components/ui/button.tsx
  src/shared/model/styles/globals.css
Labels: 🔨 refactor

#12 Fix : MoreMenu 터치 이벤트 버블링 수정
  src/shared/components/MoreMenu/MoreMenu.tsx
  src/shared/components/layout/Layout.tsx
  src/shared/components/ui/drawer.tsx
Labels: 🛠️ fix

#16 Feat: 플레이리스트 등록 페이지
  package-lock.json
  package.json
  src/pages/PlaylistForm/PlaylistFormPage.tsx
  src/pages/PlaylistForm/components/FormHeader.tsx
  src/pages/PlaylistForm/components/PlaylistInfoForm.tsx
  src/pages/PlaylistForm/components/Tabs.tsx
  src/pages/PlaylistForm/components/ToastContainer.tsx
  src/pages/PlaylistForm/components/VideoItem.tsx
  src/pages/PlaylistForm/components/VideoListForm.tsx
  src/pages/PlaylistForm/components/index.ts
  src/pages/PlaylistForm/hooks/index.ts
  src/pages/PlaylistForm/hooks/useDragAndDrop.ts
  src/pages/PlaylistForm/hooks/useFormNavigation.ts
  src/pages/PlaylistForm/hooks/useSubmitPlaylist.ts
  src/pages/PlaylistForm/hooks/useVideoManagement.ts
  src/pages/PlaylistForm/model/index.ts
  src/pages/PlaylistForm/model/types/index.ts
  src/pages/PlaylistForm/model/types/types.ts
  src/shared/components/BackButton/BackButton.tsx
  src/shared/components/ToastMessage/ToastMessage.tsx
  src/shared/components/layout/Layout.tsx
  src/shared/components/ui/badge.tsx
  src/shared/components/ui/button.tsx
  src/shared/components/ui/form.tsx
  src/shared/components/ui/label.tsx
  src/shared/components/ui/switch.tsx
  src/shared/components/ui/tabs.tsx
  src/shared/components/ui/textarea.tsx
  src/shared/model/utils/textLengthUtils.ts
  src/shared/model/utils/youtube.ts
  src/shared/store/toastStore.ts
Labels: 🚀 feat

#17 Feat: 로그인, 회원가입, 라우팅 등 작업
  package-lock.json
  package.json
  src/App.tsx
  src/features/playlistDetail/AuthorInfo/AuthorInfo.tsx
  src/features/playlistDetail/CommentInput/CommentInput.tsx
  src/features/playlistDetail/CommentList/CommentList.tsx
  src/features/playlistDetail/CommentList/components/CommentItem.tsx
  src/features/playlistDetail/CommentPopup/CommentPopup.tsx
  src/features/playlistDetail/CommentTrigger/CommentTrigger.tsx
  src/features/playlistDetail/LoginPrompt/LoginPrompt.tsx
  src/features/playlistDetail/PlaylistInfo/PlaylistInfo.tsx
  src/features/playlistDetail/VideoItem/VideoItem.tsx
  src/features/playlistDetail/VideoList/VideoList.tsx
  src/features/playlistDetail/VideoPlayer/VideoPlayer.tsx
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/PlaylistDetail/PlaylistDetailPage.tsx
  src/pages/Signup/SignupPage.tsx
  src/pages/WatchVideo/WatchVideoPage.tsx
  src/router.tsx
  src/router/ProtectedRouter.tsx
  src/router/router.tsx
  src/shared/components/BottomNav/BottomNav.tsx
  src/shared/components/ui/skeleton.tsx
  src/shared/model/api/auth.ts
  src/shared/model/api/comments.ts
  src/shared/model/api/playlist.ts
  src/shared/model/api/supabase.ts
  src/shared/model/api/youtube.ts
  src/shared/model/contexts/AuthContext.tsx
  src/shared/model/lib/query-client.ts
  src/shared/types/profile.ts
Labels: 🚀 feat

#5 Feat : HomePage 구현
  package-lock.json
  package.json
  src/assets/images/Overwatch_logo.png
  src/assets/images/lol-logo.png
  src/main.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Home/components/Categories/Categories.tsx
  src/pages/Home/components/Categories/Category.tsx
  src/pages/Home/components/PlaylistCard/CarouselView.tsx
  src/pages/Home/components/PlaylistCard/EmptyPlaylistCard.tsx
  src/pages/Home/components/PlaylistCard/PlaylistCard.tsx
  src/pages/Home/components/PlaylistContainer.tsx
  src/pages/Home/components/PlaylistView/PlaylistView.tsx
  src/pages/Home/constants/GAMES.ts
  src/pages/Home/constants/animation.ts
  src/pages/Home/constants/category.ts
  src/pages/Home/hooks/useCategoryFilter.ts
  src/pages/Home/hooks/useInfinitePlaylists.ts
  src/pages/Home/hooks/usePlaylistControl.ts
  src/pages/Home/hooks/usePrevious.ts
  src/pages/Home/hooks/useScrollControl.ts
  src/pages/Home/model/types.ts
  src/pages/Home/utils/limitCategoryCount.ts
  src/pages/Login/LoginPage.tsx
  src/pages/Signup/SignupPage.tsx
  src/shared/components/Avatar/Avatar.tsx
  src/shared/components/BottomNav/BottomNav.tsx
  src/shared/components/HashTag/HashTag.tsx
  src/shared/components/UserCard/UserCard.tsx
  src/shared/components/layout/Layout.tsx
  src/shared/components/stats/BookmarkIcon.tsx
  src/shared/components/stats/LikeIcon.tsx
  src/shared/components/ui/avatar.tsx
  src/shared/components/ui/badge.tsx
  src/shared/model/styles/globals.css
  src/shared/utils/getRelativeTime.ts
Labels: 🚀 feat

#20 PlaylistCard 좋아요 수, 구독자 수 관리 훅 분리
  package-lock.json
  package.json
  src/pages/Home/HomePage.tsx
  src/pages/Home/components/PlaylistCard/PlaylistCard.tsx
  src/pages/Home/hooks/useCategoryFilter.ts
  src/pages/Home/hooks/useInfinitePlaylists.ts
  src/pages/Home/model/types.ts
  src/shared/hooks/usePlayBookmark.ts
  src/shared/hooks/usePlaylistLike.ts
Labels: 🔨 refactor

#25 Feat : HomePage 스켈레톤 UI 추가
  src/pages/Home/HomePage.tsx
  src/pages/Home/components/HomePageSkeleton.tsx
Labels: 🚀 feat

#22 Feat : Profile Page 구현
  src/pages/Home/components/PlaylistCard/PlaylistCard.tsx
  src/pages/Home/model/types.ts
  src/pages/Profile/ProfilePage.tsx
  src/pages/Profile/components/ProfilePageHeader.tsx
  src/pages/Profile/components/ProfilePageSkeleton.tsx
  src/pages/Profile/components/TargetUserPlaylists/TargetUserPlaylistItem.tsx
  src/pages/Profile/components/TargetUserPlaylists/TargetUserPlaylists.tsx
  src/pages/Profile/components/UserNotFound.tsx
  src/pages/Profile/components/modal/EditProfileModal.tsx
  src/pages/Profile/components/modal/NicknameField.tsx
  src/pages/Profile/hooks/useNicknameField.ts
  src/pages/Profile/hooks/useTargetUserPlaylists.ts
  src/pages/Profile/hooks/useTargetUserProfileInfo.ts
  src/router/router.tsx
  src/shared/components/BottomNav/BottomNav.tsx
  src/shared/components/HashTag/HashTag.tsx
  src/shared/components/UserCard/UserCard.tsx
  src/shared/components/layout/Layout.tsx
  src/shared/components/ui/badge.tsx
  src/shared/components/ui/button.tsx
  src/shared/components/ui/dialog.tsx
  src/shared/components/ui/input.tsx
  src/shared/components/ui/skeleton.tsx
  src/shared/model/styles/globals.css
Labels: 🚀 feat

#28 Feat : 404 페이지 디자인
  src/pages/ErrorPage/ErrorPage.tsx
Labels: 🚀 feat

#26 Fix : ProfilePageHeader style & UserNotFound 렌더 조건 수정
  src/pages/Profile/ProfilePage.tsx
  src/pages/Profile/components/ProfilePageHeader.tsx
Labels: 🛠️ fix, 🌴 style

#30 Feat: 플레이리스트 수정 페이지 구현
  package-lock.json
  package.json
  src/pages/PlaylistForm/PlaylistFormPage.tsx
  src/pages/PlaylistForm/components/DeleteConfirmModal.tsx
  src/pages/PlaylistForm/components/FormHeader.tsx
  src/pages/PlaylistForm/components/PlaylistInfoForm.tsx
  src/pages/PlaylistForm/components/ToastContainer.tsx
  src/pages/PlaylistForm/components/index.ts
  src/pages/PlaylistForm/hooks/index.ts
  src/pages/PlaylistForm/hooks/useSubmitPlaylist.ts
  src/pages/PlaylistForm/hooks/useUpdatePlaylist.ts
  src/pages/PlaylistForm/hooks/useVideoManagement.ts
  src/pages/PlaylistForm/model/types/types.ts
  src/pages/PlaylistForm/queries/usePlaylistQuery.ts
  src/pages/PlaylistForm/services/playlistService.ts
  src/pages/Settings/Settings.tsx
  src/router/router.tsx
  src/shared/components/BottomNav/BottomNav.tsx
  src/shared/components/StatusButton/StatusButton.tsx
  src/shared/components/layout/Layout.tsx
  src/shared/components/ui/alert-dialog.tsx
  src/shared/components/ui/alert.tsx
  src/shared/components/ui/toast/ToastContainer.tsx
  src/shared/components/ui/toast/ToastMessage.tsx
  src/shared/store/userStore.ts
Labels: 🚀 feat

#32 Feat: 댓글 최종 수정
  src/features/CommentBox/components/CommentBox.tsx
  src/features/playlistDetail/AuthorInfo/AuthorInfo.tsx
  src/features/playlistDetail/CommentInput/CommentInput.tsx
  src/features/playlistDetail/CommentList/CommentList.tsx
  src/features/playlistDetail/CommentList/components/CommentItem.tsx
  src/features/playlistDetail/CommentPopup/CommentPopup.tsx
  src/features/playlistDetail/CommentTrigger/CommentTrigger.tsx
  src/features/playlistDetail/LoginPrompt/LoginPrompt.tsx
  src/features/playlistDetail/PlaylistInfo/PlaylistInfo.tsx
  src/features/playlistDetail/VideoItem/VideoItem.tsx
  src/features/playlistDetail/VideoList/VideoList.tsx
  src/features/playlistDetail/VideoPlayer/VideoPlayer.tsx
  src/pages/DesignSystem/DesignSystem.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/PlaylistDetail/PlaylistDetailPage.tsx
  src/pages/PlaylistDetail/utils/countFormatter.ts
  src/pages/Signup/SignupPage.tsx
  src/pages/WatchVideo/WatchVideoPage.tsx
  src/shared/components/Avatar/Avatar.tsx
  src/shared/components/UserCard/UserCard.tsx
  src/shared/model/api/auth.ts
  src/shared/model/api/comments.ts
  src/shared/model/api/playlist.ts
  src/shared/model/api/youtube.ts
  src/shared/model/lib/query-client.ts
  src/shared/model/types/youtube.type.ts
  src/shared/services/youtubeVideoApi.ts
Labels: 🛠️ fix

#36 Feat: 플레이리스트 컬렉션 페이지 구현
  package-lock.json
  src/pages/PlaylistCollection/PlaylistCollectionpage.tsx
  src/pages/PlaylistCollection/components/Card.tsx
  src/pages/PlaylistCollection/components/CardList.tsx
  src/pages/PlaylistCollection/components/CardSkeleton.tsx
  src/pages/PlaylistCollection/components/DeleteConfirmModal.tsx
  src/pages/PlaylistCollection/components/PlaylistLoadingFallback.tsx
  src/pages/PlaylistCollection/components/PlaylistMoreMenu.tsx
  src/pages/PlaylistCollection/components/Tab.tsx
  src/pages/PlaylistCollection/components/index.ts
  src/pages/PlaylistCollection/hooks/index.ts
  src/pages/PlaylistCollection/hooks/useInfiniteScroll.ts
  src/pages/PlaylistCollection/hooks/usePlaylistCollection.ts
  src/pages/PlaylistCollection/model/index.ts
  src/pages/PlaylistCollection/model/types/index.ts
  src/pages/PlaylistCollection/model/types/types.ts
  src/pages/PlaylistCollection/model/utils/index.ts
  src/pages/PlaylistCollection/model/utils/transformers.ts
  src/pages/PlaylistCollection/queries/playlistCollectionQueries.ts
  src/pages/PlaylistCollection/services/playlistCollectionService.ts
  src/pages/PlaylistForm/PlaylistFormPage.tsx
  src/pages/PlaylistForm/components/FormLoadingFallback.tsx
  src/pages/PlaylistForm/components/index.ts
  src/pages/PlaylistForm/hooks/useSubmitPlaylist.ts
  src/pages/PlaylistForm/queries/usePlaylistQuery.ts
  src/shared/components/ErrorBoundary.tsx
  src/shared/model/contexts/AuthContext.tsx
  src/shared/store/userStore.ts
Labels: 🚀 feat

#37 Fix : user_metadata에 변경한 닉네임이 반영되도록 수정
  src/pages/Profile/components/modal/EditProfileModal.tsx
  src/shared/model/api/auth.ts
Labels: 🛠️ fix

#45 Feat: Web Vitlas 측정 기능
  index.html
  public/favicon-svgrepo-com.svg
  public/favicon.svg
  src/App.tsx
  src/main.tsx
  src/pages/Profile/hooks/useNicknameField.ts
  src/pages/Settings/Settings.tsx
  src/shared/components/WebVitalsMonitor/WebVitalsMonitor.tsx
  src/shared/components/WebVitalsMonitor/reportWebVitals.ts
Labels: 🚀 feat

#40 레이아웃 상대적 단위로 변경하여 반응형 개선
  index.html
  public/images/header_logo.webp
  public/images/logo.svg
  public/images/logo.webp
  src/pages/DesignSystem/DesignSystem.tsx
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Home/components/Categories/Categories.tsx
  src/pages/Home/components/Categories/Category.tsx
  src/pages/Home/components/PlaylistCard/CarouselView.tsx
  src/pages/Home/components/PlaylistCard/EmptyPlaylistCard.tsx
  src/pages/Home/components/PlaylistCard/PlaylistCard.tsx
  src/pages/Home/components/PlaylistContainer.tsx
  src/pages/Home/components/PlaylistView/PlaylistView.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/PlaylistCollection/PlaylistCollectionpage.tsx
  src/pages/PlaylistCollection/components/Card.tsx
  src/pages/PlaylistCollection/components/CardList.tsx
  src/pages/PlaylistCollection/components/PlaylistMoreMenu.tsx
  src/pages/PlaylistCollection/components/Tab.tsx
  src/pages/PlaylistDetail/PlaylistDetailPage.tsx
  src/pages/PlaylistDetail/components/AuthorInfo/AuthorInfo.tsx
  src/pages/PlaylistDetail/components/CommentInput/CommentInput.tsx
  src/pages/PlaylistDetail/components/CommentList/CommentList.tsx
  src/pages/PlaylistDetail/components/CommentList/components/CommentItem.tsx
  src/pages/PlaylistDetail/components/CommentPopup/CommentPopup.tsx
  src/pages/PlaylistDetail/components/CommentTrigger/CommentTrigger.tsx
  src/pages/PlaylistDetail/components/LoginPrompt/LoginPrompt.tsx
  src/pages/PlaylistDetail/components/PlaylistInfo/PlaylistInfo.tsx
  src/pages/PlaylistDetail/components/VideoItem/VideoItem.tsx
  src/pages/PlaylistDetail/components/VideoList/VideoList.tsx
  src/pages/PlaylistDetail/components/VideoPlayer/VideoPlayer.tsx
  src/pages/PlaylistForm/PlaylistFormPage.tsx
  src/pages/PlaylistForm/components/PlaylistInfoForm.tsx
  src/pages/PlaylistForm/components/VideoListForm.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/Profile/components/TargetUserPlaylists/TargetUserPlaylistItem.tsx
  src/pages/Profile/components/TargetUserPlaylists/TargetUserPlaylists.tsx
  src/pages/Profile/components/modal/EditProfileModal.tsx
  src/pages/Settings/Settings.tsx
  src/pages/Signup/SignupPage.tsx
  src/shared/components/Avatar/Avatar.tsx
  src/shared/components/BottomNav/BottomNav.tsx
  src/shared/components/HashTag/HashTag.tsx
  src/shared/components/UserCard/UserCard.tsx
  src/shared/components/layout/Layout.tsx
  src/shared/components/stats/BookmarkIcon.tsx
  src/shared/components/stats/LikeIcon.tsx
  src/shared/components/ui/dialog.tsx
  src/shared/components/ui/form.tsx
  src/shared/model/api/auth.ts
  src/shared/model/api/playlist.ts
  src/shared/model/api/supabase.ts
  vite.config.ts
Labels: 🌴 style

#43 Fix : HomePage 해시태그 없는 플레이리스트 데이터 렌더 이슈 해결
  src/pages/Home/components/PlaylistCard/CarouselView.tsx
  src/pages/Home/components/PlaylistCard/PlaylistCard.tsx
  src/pages/Home/hooks/useInfinitePlaylists.ts
  src/pages/Home/model/types.ts
  src/pages/PlaylistDetail/PlaylistDetailPage.tsx
  src/pages/PlaylistDetail/components/AuthorInfo/AuthorInfo.tsx
  src/shared/hooks/usePlaylistBookmark.ts
Labels: 🛠️ fix

#50 Refactor : Profile Page
  src/features/playlistDetail/AuthorInfo/AuthorInfo.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Home/components/PlaylistSection.tsx
  src/pages/Home/queries/homePageQueryKeys.ts
  src/pages/Home/queries/useInfinitePlaylists.ts
  src/pages/PlaylistDetail/PlaylistDetailPage.tsx
  src/pages/Profile/ProfilePage.tsx
  src/pages/Profile/components/PlaylistSection/PlaylistSection.tsx
  src/pages/Profile/components/ProfileHeader/ProfileHeaderSection.tsx
  src/pages/Profile/components/ProfileHeader/ProfilePageHeader.tsx
  src/pages/Profile/components/ProfilePageSkeleton.tsx
  src/pages/Profile/components/TargetUserPlaylists/TargetUserPlaylistItem.tsx
  src/pages/Profile/components/TargetUserPlaylists/TargetUserPlaylists.tsx
  src/pages/Profile/components/modal/EditProfileModal.tsx
  src/pages/Profile/components/modal/NicknameField.tsx
  src/pages/Profile/components/skeletons/ProfilePageSkeleton.tsx
  src/pages/Profile/hooks/useCachedPlaylistCount.ts
  src/pages/Profile/hooks/useNicknameField.ts
  src/pages/Profile/hooks/useTargetUserProfileInfo.ts
  src/pages/Profile/model/type.ts
  src/pages/Profile/queries/getCachedPlaylists.ts
  src/pages/Profile/queries/profilePageQueryKeys.ts
  src/pages/Profile/queries/useTargetUserPlaylists.ts
  src/pages/Profile/queries/useTargetUserProfileInfo.ts
  src/pages/Profile/queries/useUpdateNickname.ts
  src/pages/Profile/services/nicknameServiece.ts
  src/pages/Profile/services/playlistWithItemsService.ts
  src/pages/Settings/Settings.tsx
  src/shared/components/ErrorBoundary.tsx
  src/shared/components/SkeletonAnimation.tsx
  src/shared/components/UserCard/UserCard.tsx
  src/shared/model/api/auth.ts
  src/shared/model/utils/validation.ts
Labels: 🔨 refactor

#57 Refactor: searchBar 서비스로직, 뒤로가기 수정
  src/pages/Home/components/SearchBar/SearchBar.tsx
  src/pages/Home/components/SearchBar/services/searchbarService.ts
  src/shared/animations/SlideContainer.tsx
  src/shared/animations/index.ts
Labels: 🔨 refactor

#59 Fix : 로그아웃 오류 해결
  netlify.toml
  src/pages/Settings/Settings.tsx
  src/shared/model/api/auth.ts
Labels: 🛠️ fix

#63 프로필 변경 기능 구현
  src/pages/Home/components/PlaylistCard/PlaylistCard.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/PlaylistCollection/PlaylistCollectionpage.tsx
  src/pages/PlaylistCollection/components/Card.tsx
  src/pages/PlaylistCollection/components/CardList.tsx
  src/pages/PlaylistCollection/components/CardListSkeleton.tsx
  src/pages/PlaylistCollection/components/CardSkeleton.tsx
  src/pages/PlaylistCollection/components/PlaylistContent.tsx
  src/pages/PlaylistCollection/components/PlaylistLoadingFallback.tsx
  src/pages/PlaylistCollection/components/index.ts
  src/pages/PlaylistCollection/queries/playlistCollectionQuery.ts
  src/pages/PlaylistDetail/PlaylistDetailPage.tsx
  src/pages/PlaylistDetail/components/CommentInput/CommentInput.tsx
  src/pages/PlaylistDetail/components/CommentList/components/CommentItem.tsx
  src/pages/PlaylistDetail/components/CommentTrigger/CommentTrigger.tsx
  src/pages/PlaylistForm/components/PlaylistFormContent.tsx
  src/pages/PlaylistForm/components/PlaylistInfoForm.tsx
  src/pages/PlaylistForm/hooks/useUpdatePlaylist.ts
  src/pages/PlaylistForm/queries/playlistQuery.ts
  src/pages/PlaylistForm/services/playlistService.ts
  src/pages/Profile/components/ProfileHeader/ProfilePageHeader.tsx
  src/pages/Profile/components/modal/EditProfileModal.tsx
  src/pages/Profile/hooks/useCachedPlaylistCount.ts
  src/pages/Profile/model/type.ts
  src/pages/Profile/queries/profileQuery.ts
  src/pages/Profile/services/profileService.ts
  src/pages/Settings/Settings.tsx
  src/shared/components/Avatar/Avatar.tsx
  src/shared/components/PageLoadingFallback/PageLoadingFallback.tsx
  src/shared/components/UserCard/AvatarContainer.tsx
  src/shared/components/UserCard/UserCard.tsx
  src/shared/components/ui/dialog.tsx
  src/shared/hooks/usePlaylistBookmark.ts
  src/shared/model/api/playlist.ts
  src/shared/model/contexts/AuthContext.tsx
  src/shared/model/lib/queryClient.ts
  src/shared/model/utils/checkSupabaseError.ts
  src/shared/model/utils/mapErrorMessage.ts
  src/shared/model/utils/toast.ts
  src/shared/queries/profileSharedQuery.ts
  src/shared/queries/profileSharedQueryKeys.ts
  src/shared/queries/usePlaylistBookmarkMutation.ts
  src/shared/services/profileSharedService.ts
  src/shared/store/userStore.ts
Labels: 🚀 feat, 🔨 refactor
